Mfkey qol improvements
GameTec-live/ChameleonUltraGUI pull request #192
Opened 2023-09-01 19:29 UTC by GameTec-live

mfkey32 now with saving! Save to file, New Dictionary or Existing Dictionary with ease....

2023-09-01 19:39 UTC, Foxushka requested changes

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
>                controller.text +=
As I said remove whole textbox

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +    String filecontents = "";
fileContents

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +  String convertUintToDictFile(List<Uint8List> keys) {
convertKeysToDictFile

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +      for (var v in keys) Object.hashAll(v): v
for (var key in keys)

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +                                              convertUintToDictFile(keys);
fileContents

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +                                              fileName: '${name}.dict',
.dic

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +                                                ext: 'dict',
dic

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +                                            "Append to existing Dictionary"),
Add to existing dictionary

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +                                            name: "Recovered Keys",
Use UID here

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +                                              return DictionaryEditMenu(dict: dict, isNew: true,);
DictionaryEditMenu(dict: dict, isNew: true)

2023-09-01 19:39 UTC, Foxushka commented on chameleonultragui/lib/gui/page/mfkey32.dart
> +                                        child: Text("Save to new Dictionary"),
Save to new dictionary

2023-09-01 19:40 UTC, Foxushka commented
And add translation strings

2023-09-01 19:57 UTC, GameTec-live commented
translation is @aruznieto s job... neither yours nor my :p

2023-09-01 20:56 UTC, aruznieto commented
> translation is @aruznieto s job... neither yours nor my :p

For this reasson i said that I preferred to use my Crowdin project...

2023-09-03 15:18 UTC, Akisame-AI approved these changes
It works. 
I get a random key when reading with the phone (D3F7D3F7D3F7) but also a valid key. 
Nothing breaks so I approve.

2023-09-03 15:20 UTC, merged